allowBuilds:
  '@nestjs/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - brace-expansion@1.1.18
  - esbuild@0.28.2
  - form-data@4.0.6
  - undici@6.28.0
  - undici@7.29.0

overrides:
  esbuild: 0.28.2

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver

minimumReleaseAgeExcludePrune: true
