allowBuilds:
  '@nestjs/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.3'
  - vue-tsc@3.3.3

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
